name: Deploy to On-Premise Server

on:
  push:
    branches:
      - OnPremiseTest  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: windows-latest  # Specify the operating system for the job

    steps:
      # - uses: actions/checkout@v4

      # - name: Setup MSBuild path
      #   uses: microsoft/setup-msbuild@v1.0.2

      # - name: Setup NuGet
      #   uses: NuGet/setup-nuget@v1.0.5

      # - name: Restore NuGet packages
      #   run: nuget restore

      # - name: Publish to folder
      #   run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Copy files to on-premise server        
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: apps.ilogixphils.com
          username: renebert
          password: iLogix123456!
         

      - name: Restart IIS
        run: restart-webitempool -name "DefaultAppPool"  # Restart the DefaultAppPool in IIS
